metadata:
  slug: 'opencost'
  name: 'Cost Monitoring'
  description: 'OpenCost is a cost management tool for Kubernetes.'
  categories: ['Cost Management']
  # releaseDate: 
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/opencost/logo-dark.png'
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/opencost/logo.png'
  detailUrl: 'https://addons.kaops.net/opencost'
  externalUrl: 'https://opencost.github.io/opencost-helm-chart'
  isProduction: true
  installTargets:
    hub: true
    hubRequired: true
    edge: true

# forms could be used with the Form Options choser you see in the Dialog now 
# (only as needed, if needed..otherwise only default is used)
forms: 
  - slug: default
    label: 'OpenCost configuration'
    description: 'Open source cost monitoring for cloud native environments'
    steps:
      - slug: 'opencost'
        variableSlugs:
        - 'cloudIntegrationSecret'
        - 'cloudProviderApiKey'
        - 'defaultClusterId'
        - 'releaseLabel'
        - 'prometheusServiceName'
        ui:
          label: 'OpenCost' 
        
  
variables:
  - slug: 'cloudIntegrationSecret'
    name: 'cloudIntegrationSecret'
    path: 'opencost.opencost.cloudIntegrationSecret'
    forms: ['default']
    ui:
      type: 'secret'
      placeholder: 'Cloud Integration Secret'
      validation: 'required'
  - slug: 'cloudProviderApiKey'
    name: 'cloudProviderApiKey'
    path: 'opencost.opencost.exporter.cloudProviderApiKey'
    forms: ['default']
    ui:
      type: 'text'
      label: 'Cloud Provider API Key'
  - slug: 'defaultClusterId'
    name: 'defaultClusterId'
    path: 'opencost.opencost.exporter.defaultClusterId'
    forms: ['default']
    ui:
      type: 'text'
      label: 'Default Cluster ID'
system:
  - path: 'opencost.opencost.metrics.serviceMonitor.namespace'
    value: '${system.cluster.namespace}'
  - path: 'opencost.opencost.prometheus.internal.namespaceName'
    value: '${system.cluster.namespace}'
  - path: 'opencost.opencost.metrics.serviceMonitor.additionalLabels.release'
    value: '${system.observabilityInfo.releaseName}'
  - path: 'opencost.opencost.prometheus.internal.serviceName'
    value: '${system.observabilityInfo.prometheusServiceName}'
  - path: 'cluster.type'
    value: '${system.cluster.clusterRole}'

output:
  - name: OpenCost Dashboard
    description: 'Grafana dashboard title for OpenCost'
    value: 'OpenCost / Overview'
    type: 'text'
    slug: default

dependencies:
  networkFeatures:
    - slug: 'grafana'
      name: 'Grafana'
      required: false
    - slug: 'sealed-secrets'
      name: 'SealedSecrets'
      required: true
