metadata:
  slug: 'opencost'
  name: 'OpenCost'
  description: 'OpenCost is a cost management tool for Kubernetes.'
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/opencost/logo-dark.png'
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/opencost/logo.png'
  detailUrl: 'https://addons.kaops.net/opencost'
  externalUrl: 'https://opencost.github.io/opencost-helm-chart'
  installTargets:
    hub: true
    hubRequired: true
    edge: false

# forms could be used with the Form Options choser you see in the Dialog now 
# (only as needed, if needed..otherwise only default is used)
forms: 
  - slug: defaultOLD
    label: 'Standard form'
    description: 'Something cool to say about it, maybe'
    # type: standard
    steps:
      - slug: 'step1'
        # tags: true
        # tagsAfter: name
        variableSlugs:
        - 'foo'
        ui:
          label: 'Step 1'  
        # - 'nh_tags' # does this work to indicate nethopper tags (and ordering)?
      - slug: 'step2'
        variableSlugs:
        - 'bar'
        ui:
          label: 'Step 2'
  - slug: default
    label: 'Standard form'
    description: 'Something cool to say about it, maybe'
        
  # - slug: tags
  #   schemaKey: tags
  #   label: 'Tag Only'
  #   type: tags
  # - slug: secret
  #   type: secret
  
variables:
  - slug: 'existingSecret'
    # name: 'existingSecret'
    path: 'cloudIntegrationSecret.existingSecret'
    forms: ['default']
    # schemaLookupKey: 'secret'
    #requiredSecretKeys:
     #- 'foo'
     #- 'bar'
    ui:
      type: 'secret'
      # modelValue: '$fields.foo'
      # label: 'Foo'
      placeholder: 'Choose an existing Secret'
      # help: ''
      validation: 'required'
  # - slug: 'test1'
  #   path: 'route.spout.test1'
  #   forms: ['default']
  #   isCreateOnly: true
  #   ui:
  #     label: 'Test 1'
  #     type: 'text'
  # - slug: 'test2'
  #   path: 'route.spout.test2'
  #   forms: ['default']
  #   ui:
  #     label: 'Test 2'
  #     type: 'text'
  # - slug: 'bar'
  #   path: 'path.bar'
  #   forms: ['default']
  #   ui:
  #     type: 'text'
  #     label: 'Bar'
  # - slug: 'baz'
  #   path: 'path.baz'
  #   forms: ['default']
  #   ui:
  #     type: 'text'
  #     label: 'Baz'

dependencies:
  networkFeatures:
    - slug: 'grafana'
      name: 'Grafana'
      required: false
    - slug: 'sealed-secrets'
      name: 'SealedSecrets'
      required: true
