metadata:
  slug: "opencost"
  displayName: "OpenCost"
  logoURL: "https://opencost.github.io/opencost-helm-chart/images/logo.png"
  description: "OpenCost is a cost management tool for Kubernetes."
  infoUrl: "https://opencost.github.io/opencost-helm-chart"
  
forms: 
  - name: "myform"
    description: "Form for namespace"
    type: standard
  - name: "secrets"
    type: secret
  
variables:
  - name: "existingSecret"
    path: "cloudIntegrationSecret.existingSecret"
    description: "Name of existing secret for cloud integration"
    type: "text"
    label: "Existing Secret"
    required: false
  - name: "sealedSecretMetadata"
    path: "cloudIntegrationSecret."
    description: "Name of existing secret for cloud integration"
    type: "text"
    label: "Namespace"
    required: false
  - name: "sealedSecretSpec"
    path: "cloudIntegrationSecret."
    description: "Name of existing secret for cloud integration"
    type: "text"
    required: false

dependencies:
    features:
      - name: 'grafana'
        required: false
      - name: 'sealed-secrets'
        required: true