metadata:
  slug: gdrive-gcs-sync
  name: GDrive GCS Sync
  description: Addon to sync files between Google Drive and Google Cloud Storage.
  logoUrlDark: "https://upload.wikimedia.org/wikipedia/commons/d/da/Google_Drive_logo.png"
  logoUrlLight: "https://upload.wikimedia.org/wikipedia/commons/d/da/Google_Drive_logo.png"
  detailUrl: "https://addons.kaops.net/gdrive-gcs-sync/"
  externalUrl: "https://kaops.net"
  installTargets:
    infoMessage: Sync files between Google Drive and Google Cloud Storage
  categories: ['Playground']

forms:
  - slug: default
    label: Configuration

variables:
  - slug: GOOGLE_APPLICATION_CREDENTIALS_SECRET_REF
    path: "gdrive-gcs-sync.env.GOOGLE_APPLICATION_CREDENTIALS_SECRET_REF"
    forms: [default]
    ui:
      type: secret
      label: Google Application Credentials
      help: Base64 encoded Google Application Credentials JSON file.
      validation: base64
  - slug: DRIVE_FOLDER_ID
    path: "gdrive-gcs-sync.env.DRIVE_FOLDER_ID"
    forms: [default]
    ui:
      type: text
      label: "Source: GDrive Folder ID"
      help: ID of the Google Drive folder to sync.
      validation: required
  - slug: GCS_BUCKET_NAME
    path: "gdrive-gcs-sync.env.GCS_BUCKET_NAME"
    forms: [default]
    ui:
      type: text
      label: "Destination: GCS Bucket Name"
      help: Name of the GCS bucket sync target.
      validation: required
  - slug: GOOGLE_API_SCOPES
    path: "gdrive-gcs-sync.env.GOOGLE_API_SCOPES"
    forms: [default]
    ui:
      type: text
      label: API Scopes
      value: "https://www.googleapis.com/auth/drive.readonly"
      help: Comma separated list of API scopes to request.
      validation: required
  - slug: ALLOWED_EXTENSIONS
    path: "gdrive-gcs-sync.env.ALLOWED_EXTENSIONS"
    forms: [default]
    ui:
      type: text
      label: Allowed Extensions
      validation: "matches:/^([a-zA-Z0-9]+(,\s*[a-zA-Z0-9]+\s*)*)?$/"
      validation-visibility: "live"
      validation-messages: 
        - fileExtensions: 'Invalid format. Use comma-separated extensions like: jpg,png'
      help: Comma separated list of allowed file extensions to sync. No dots.
