metadata:
  slug: gdrive-gcs-sync
  name: GDrive GCS Sync
  description: Addon to sync files between Google Drive and Google Cloud Storage.
  logoUrlDark: "https://en.wikipedia.org/wiki/Google_Drive#/media/File:Google_Drive_icon_(2020).svg"
  logoUrlLight: "https://en.wikipedia.org/wiki/Google_Drive#/media/File:Google_Drive_icon_(2020).svg"
  detailUrl: "https://addons.kaops.net/gdrive-gcs-sync/"
  externalUrl: "https://kaops.net"
  installTargets:
    infoMessage: Sync files between Google Drive and Google Cloud Storage
  categories: ['Playground']

forms:
  - slug: default
    label: Configuration

variables:
  - slug: test
    path: "test"
    forms: ["default"]
    ui:
      type: group
      children:
        - type: text
          label: test
          name: test