metadata:
  slug: 'ollama'
  name: 'Ollama'
  description: 'Deploy and run on Kubernetes clusters to manage LLMs in containerized environments.'
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/ollama/logo-dark.png' # TODO
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/ollama/logo.png' # TODO
  detailUrl: 'https://addons.kaops.net/ollama/'
  externalUrl: 'https://ollama.com/'
  isProduction: false
  installTargets:
    hub: true
    hubRequired: true
    edge: false

forms: 
  - slug: default
    label: 'Ollama configuration'
    description: 'Deploying Ollama on Kubernetes provides organizations with a powerful way to leverage LLMs while maintaining control over their infrastructure and data privacy.'
variables:
system:

    
