{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "private-ai.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.ingress.oauth2Proxy.enabled .Values.ingress.oauth2Proxy.authUrl .Values.ingress.oauth2Proxy.authSignin }}
    nginx.ingress.kubernetes.io/auth-url: {{ .Values.ingress.oauth2Proxy.authUrl | quote }}
    nginx.ingress.kubernetes.io/auth-signin: {{ .Values.ingress.oauth2Proxy.authSignin | quote }}
    nginx.ingress.kubernetes.io/auth-response-headers: {{ .Values.ingress.oauth2Proxy.authResponseHeaders | quote }}
    {{- end }}
spec:
  {{- with .Values.ingress.class }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host | quote }}
      {{- range .Values.ingress.additionalHosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ default (printf "%s-tls" .Release.Name) .Values.ingress.existingSecret }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              name: http
  {{- range .Values.ingress.additionalHosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              name: http
  {{- end }}
{{- end }}
