apiVersion: v1
kind: Pod
metadata:
  name: open-webui-0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: open-webui
spec:
  # Only explicit settings that differ from defaults or are required
  automountServiceAccountToken: false
  enableServiceLinks: false
  {{- if .Values.serviceAccount }}
  {{- if .Values.serviceAccount.create | default true }}
  serviceAccount: {{ include "private-ai.serviceAccountName" . }}
  serviceAccountName: {{ include "private-ai.serviceAccountName" . }}
  {{- end }}
  {{- end }}
  
  # Init container - conditional based on open-webui configuration
  {{- if index .Values "open-webui" }}
  {{- $openWebUI := index .Values "open-webui" }}
  {{- if $openWebUI.initContainer }}
  {{- if $openWebUI.initContainer.enabled | default true }}
  initContainers:
  - name: copy-app-data
    image: {{ $openWebUI.image.repository }}:{{ $openWebUI.image.tag }}
    imagePullPolicy: {{ $openWebUI.image.pullPolicy }}
    command:
    - sh
    - -c
    - cp -R -n /app/backend/data/* /tmp/app-data/
    volumeMounts:
    - mountPath: /tmp/app-data
      name: data
  {{- end }}
  {{- end }}
  {{- end }}
  
  containers:
  - name: open-webui
    {{- $openWebUI := index .Values "open-webui" }}
    image: {{ $openWebUI.image.repository }}:{{ $openWebUI.image.tag }}
    imagePullPolicy: {{ $openWebUI.image.pullPolicy }}
    {{- if $openWebUI.tty | default true }}
    tty: true
    {{- end }}
    ports:
    - containerPort: 8080
      name: http
    
    # Environment variables from your values structure
    env:
    {{- $openWebUI := index .Values "open-webui" }}
    {{- range $openWebUI.extraEnvVars }}
    - name: {{ .name }}
      {{- if .value }}
      value: {{ .value | quote }}
      {{- else if .valueFrom }}
      valueFrom:
        {{- if .valueFrom.secretKeyRef }}
        secretKeyRef:
          name: {{ .valueFrom.secretKeyRef.name }}
          key: {{ .valueFrom.secretKeyRef.key }}
        {{- else if .valueFrom.configMapKeyRef }}
        configMapKeyRef:
          name: {{ .valueFrom.configMapKeyRef.name }}
          key: {{ .valueFrom.configMapKeyRef.key }}
        {{- end }}
      {{- end }}
    {{- end }}
    
    # Data ingestion secrets - Single secret with different keys approach
    {{- if .Values.dataIngestion.enabled }}
    {{- $dataIngestionSecret := .Values.dataIngestion.config.dataIngestionSecretsRef | default .Values.global.dataIngestionSecretsRef | default "shared-secrets-data-ingestion" }}
    
    # All data ingestion secrets from single secret with individual keys
    - name: ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: ENCRYPTION_KEY
    - name: GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: GOOGLE_CLIENT_ID
    - name: GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: GOOGLE_CLIENT_SECRET
    - name: GOOGLE_REDIRECT_URI
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: GOOGLE_REDIRECT_URI
    - name: MICROSOFT_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: MICROSOFT_CLIENT_ID
    - name: MICROSOFT_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: MICROSOFT_CLIENT_SECRET
    - name: MICROSOFT_TENANT_ID
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: MICROSOFT_TENANT_ID
    - name: MICROSOFT_REDIRECT_URI
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: MICROSOFT_REDIRECT_URI
    - name: SLACK_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: SLACK_CLIENT_ID
    - name: SLACK_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: SLACK_CLIENT_SECRET
    - name: SLACK_REDIRECT_URI
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: SLACK_REDIRECT_URI
    - name: ATLASSIAN_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: ATLASSIAN_CLIENT_ID
    - name: ATLASSIAN_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: {{ $dataIngestionSecret }}
          key: ATLASSIAN_CLIENT_SECRET
    {{- end }}
    
    # Global Google Application Credentials (if provided separately)
    {{- if .Values.global.googleApplicationCredentialsSecretRef }}
    - name: GOOGLE_APPLICATION_CREDENTIALS_BASE64
      valueFrom:
        secretKeyRef:
          name: {{ .Values.backups.googleApplicationCredentialsSecretRef | default .Values.global.googleApplicationCredentialsSecretRef }}
          key: GOOGLE_APPLICATION_CREDENTIALS_BASE64
    {{- end }}
    
    # Additional custom environment variables can be added here
    {{- range $key, $value := $openWebUI.customEnvVars | default dict }}
    - name: {{ $key }}
      {{- if $value.value }}
      value: {{ $value.value | quote }}
      {{- else if $value.valueFrom }}
      valueFrom:
        {{- if $value.valueFrom.secretKeyRef }}
        secretKeyRef:
          name: {{ $value.valueFrom.secretKeyRef.name }}
          key: {{ $value.valueFrom.secretKeyRef.key }}
        {{- else if $value.valueFrom.configMapKeyRef }}
        configMapKeyRef:
          name: {{ $value.valueFrom.configMapKeyRef.name }}
          key: {{ $value.valueFrom.configMapKeyRef.key }}
        {{- end }}
      {{- end }}
    {{- end }}
    
    # Automatic environment variable loading from your values structure
    envFrom:
    {{- range $openWebUI.extraEnvFrom }}
    - {{ . | toYaml | nindent 6 }}
    {{- end }}
    
    # Additional envFrom sources
    {{- if .Values.global.extraEnvVarsCM }}
    - configMapRef:
        name: {{ .Values.global.extraEnvVarsCM }}
    {{- end }}
    {{- if .Values.global.extraEnvVarsSecret }}
    - secretRef:
        name: {{ .Values.global.extraEnvVarsSecret }}
    {{- end }}
    
    # Volume mounts
    volumeMounts:
    - name: data
      mountPath: /app/backend/data
    {{- if $openWebUI.extraVolumeMounts }}
    {{- range $openWebUI.extraVolumeMounts }}
    - {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
    
    # Resources
    {{- if $openWebUI.resources }}
    resources:
      {{- toYaml $openWebUI.resources | nindent 6 }}
    {{- end }}
    
    # Security context
    {{- if $openWebUI.securityContext }}
    securityContext:
      {{- toYaml $openWebUI.securityContext | nindent 6 }}
    {{- end }}
    
    # Health checks
    {{- if $openWebUI.livenessProbe }}
    livenessProbe:
      {{- toYaml $openWebUI.livenessProbe | nindent 6 }}
    {{- end }}
    {{- if $openWebUI.readinessProbe }}
    readinessProbe:
      {{- toYaml $openWebUI.readinessProbe | nindent 6 }}
    {{- end }}
  
  # Volumes
  volumes:
  - name: data
    {{- $openWebUI := index .Values "open-webui" }}
    {{- if $openWebUI.persistence }}
    {{- if $openWebUI.persistence.enabled | default true }}
    persistentVolumeClaim:
      claimName: {{ $openWebUI.persistence.existingClaim | default (printf "%s-data" (include "private-ai.fullname" .)) }}
    {{- else }}
    emptyDir: {}
    {{- end }}
    {{- else }}
    emptyDir: {}
    {{- end }}
  {{- if $openWebUI.extraVolumes }}
  {{- range $openWebUI.extraVolumes }}
  - {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
  
  # Pod-level configurations - only if specified
  {{- if .Values.tolerations }}
  tolerations:
    {{- toYaml .Values.tolerations | nindent 2 }}
  {{- end }}
  
  {{- if .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 4 }}
  {{- end }}
  
  {{- if .Values.affinity }}
  affinity:
    {{- toYaml .Values.affinity | nindent 4 }}
  {{- end }}
  
  {{- if $openWebUI.podSecurityContext }}
  securityContext:
    {{- toYaml $openWebUI.podSecurityContext | nindent 4 }}
  {{- end }}

---
# Service to expose the pod
{{- if .Values.openWebUI }}
{{- if .Values.openWebUI.service }}
{{- if .Values.openWebUI.service.enabled | default true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "private-ai.fullname" . }}-webui-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: open-webui-service
  {{- if .Values.openWebUI.service.annotations }}
  annotations:
    {{- toYaml .Values.openWebUI.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.openWebUI.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.openWebUI.service.port | default 8080 }}
    targetPort: {{ .Values.openWebUI.service.targetPort | default 8080 }}
    name: http
    {{- if and (eq (.Values.openWebUI.service.type | default "ClusterIP") "NodePort") .Values.openWebUI.service.nodePort }}
    nodePort: {{ .Values.openWebUI.service.nodePort }}
    {{- end }}
  selector:
    {{- include "private-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: open-webui
{{- end }}
{{- end }}
{{- end }}