apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
data:
  postgres-password: {{ include "private-ai.randomPassword" . | b64enc | quote }}
  