{{- $randomPassword := randAlphaNum 16 -}}
{{- $existingSharedSecrets := lookup "v1" "Secret" .Release.Namespace "shared-secrets-rag" -}}
{{- $existingPostgresqlPassword := lookup "v1" "Secret" .Release.Namespace "postgresql-password" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets-rag
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
data:
  BASE_URL: {{ "http://open-webui" | b64enc }}
  SIGNUP_NAME: {{ "Admin User" | b64enc }}
  SIGNUP_EMAIL: {{ .Values.ingress.oauth2Proxy.adminEmail | b64enc }}
  SIGNUP_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  ENABLE_OAUTH_SIGNUP: {{ .Values.ingress.oauth2Proxy.enabled | quote | b64enc }}
  JWT_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- if $existingSharedSecrets }}
  DATABASE_URL: {{ $existingSharedSecrets.data.DATABASE_URL }}
  POSTGRES_CREDENTIALS: {{ $existingSharedSecrets.data.POSTGRES_CREDENTIALS }}
  {{- else if .Values.rag.postgresHost }}
  {{- else}}
  DATABASE_URL: {{ (print "postgresql://" .Values.global.postgresql.auth.username ":" $randomPassword "@" .Values.rag.postgresHost ":5432/open-webui") | b64enc | quote }}
  POSTGRES_CREDENTIALS: {{ $randomPassword | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
data:
  {{- if $existingPostgresqlPassword }}
  postgresPassword: {{ $existingPostgresqlPassword.postgresPassword }}
  {{- else }}
  postgresPassword: {{ $randomPassword | b64enc | quote }}
  {{- end }}