{{ $randomPassword := randAlphaNum 16 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets-rag
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.rag.secretArgocdHook }}
data:
  BASE_URL: {{ "http://open-webui" | b64enc }}
  SIGNUP_NAME: {{ "Admin User" | b64enc }}
  SIGNUP_EMAIL: {{ .Values.ingress.oauth2Proxy.adminEmail | b64enc }}
  SIGNUP_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  ENABLE_OAUTH_SIGNUP: {{ .Values.ingress.oauth2Proxy.enabled | quote | b64enc }}
  JWT_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  DATABASE_URL: {{ (print "postgresql://" .Values.global.postgresql.auth.username ":" $randomPassword "@" .Values.rag.postgresHost ":5432/postgres") | b64enc | quote }}
  POSTGRES_CREDENTIALS: {{ $randomPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.rag.secretArgocdHook }}
data:
  postgresPassword: {{ $randomPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets-data-ingestion
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.rag.secretArgocdHook }}
data:
  ENCRYPTION_KEY: {{ .Values.dataIngestion.config.encryptionKey | b64enc | quote }}
  SLACK_CLIENT_ID: {{ .Values.dataIngestion.config.slackClientId | b64enc | quote }}
  SLACK_CLIENT_SECRET: {{ .Values.dataIngestion.config.slackClientSecret | b64enc | quote }}
  SLACK_REDIRECT_URI: {{ .Values.dataIngestion.config.slackRedirectUrl | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.dataIngestion.config.googleClientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.dataIngestion.config.googleClientSecret | b64enc | quote }}
  GOOGLE_REDIRECT_URI: {{ .Values.dataIngestion.config.googleRedirectUrl | b64enc | quote }}
  MICROSOFT_CLIENT_ID: {{ .Values.dataIngestion.config.microsoftClientId | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.dataIngestion.config.microsoftClientSecret | b64enc | quote }}
  MICROSOFT_TENANT_ID: {{ .Values.dataIngestion.config.microsoftTenantId | b64enc | quote }}
  MICROSOFT_REDIRECT_URI: {{ .Values.dataIngestion.config.microsoftRedirectUrl | b64enc | quote }}
  ATLASSIAN_CLIENT_ID: {{ .Values.dataIngestion.config.atlassianClientId | b64enc | quote }}
  ATLASSIAN_CLIENT_SECRET: {{ .Values.dataIngestion.config.atlassianClientSecret | b64enc | quote }}
  ATLASSIAN_REDIRECT_URL: {{ .Values.dataIngestion.config.atlassianRedirectUrl | b64enc | quote }}
  GCS_SERVICE_ACCOUNT_BASE64: {{ .Values.dataIngestion.config.gcsServiceAccountCredentials | b64enc | quote }}