{{- $randomPassword := randAlphaNum 16 }}
{{- $randomNeo4jPassword := randAlphaNum 16 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets-rag
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.secretArgocdHook }}
data:
  BASE_URL: {{ "http://open-webui" | b64enc }}
  SIGNUP_NAME: {{ "Admin User" | b64enc }}
  SIGNUP_EMAIL: {{ .Values.ingress.oauth2Proxy.adminEmail | b64enc }}
  SIGNUP_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  ENABLE_OAUTH_SIGNUP: {{ .Values.ingress.oauth2Proxy.enabled | quote | b64enc }}
  JWT_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  DATABASE_URL: {{ (print "postgresql://" .Values.global.postgresql.auth.username ":" $randomPassword "@" .Values.rag.postgresHost ":5432/postgres") | b64enc | quote }}
  POSTGRES_CREDENTIALS: {{ $randomPassword | b64enc | quote }}
  NEO4J_AUTH: {{ (print "neo4j/" $randomNeo4jPassword) | b64enc | quote }}
  NEO4J_PASSWORD: {{ $randomNeo4jPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.secretArgocdHook }}
data:
  postgresPassword: {{ $randomPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-password
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.secretArgocdHook }}
data:
  NEO4J_AUTH: {{ (print "neo4j/" $randomNeo4jPassword) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: data-ingestion-creds
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.secretArgocdHook }}
data:
  {{- range $key, $value := .Values.dataIngestion.config.dataIngestionCredentialsRef }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}