{{ $randomPassword := randAlphaNum 16 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets-rag
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.rag.secretArgocdHook }}
data:
  BASE_URL: {{ "http://open-webui" | b64enc }}
  SIGNUP_NAME: {{ "Admin User" | b64enc }}
  SIGNUP_EMAIL: {{ .Values.ingress.oauth2Proxy.adminEmail | b64enc }}
  SIGNUP_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  ENABLE_OAUTH_SIGNUP: {{ .Values.ingress.oauth2Proxy.enabled | quote | b64enc }}
  JWT_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  DATABASE_URL: {{ (print "postgresql://" .Values.global.postgresql.auth.username ":" $randomPassword "@" .Values.rag.postgresHost ":5432/postgres") | b64enc | quote }}
  POSTGRES_CREDENTIALS: {{ $randomPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  labels: 
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.rag.secretArgocdHook }}
data:
  postgresPassword: {{ $randomPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets-data-ingestion
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  {{- with .Values.dataIngestion.config }}
  {{- if .encryptionKey }}
  ENCRYPTION_KEY: {{ .encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .slackClientId }}
  SLACK_CLIENT_ID: {{ .slackClientId | b64enc | quote }}
  {{- end }}
  {{- if .slackClientSecret }}
  SLACK_CLIENT_SECRET: {{ .slackClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .slackRedirectUrl }}
  SLACK_REDIRECT_URI: {{ .slackRedirectUrl | b64enc | quote }}
  {{- end }}
  {{- if .googleClientId }}
  GOOGLE_CLIENT_ID: {{ .googleClientId | b64enc | quote }}
  {{- end }}
  {{- if .googleClientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .googleClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .googleRedirectUrl }}
  GOOGLE_REDIRECT_URI: {{ .googleRedirectUrl | b64enc | quote }}
  {{- end }}
  {{- if .microsoftClientId }}
  MICROSOFT_CLIENT_ID: {{ .microsoftClientId | b64enc | quote }}
  {{- end }}
  {{- if .microsoftClientSecret }}
  MICROSOFT_CLIENT_SECRET: {{ .microsoftClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .microsoftTenantId }}
  MICROSOFT_TENANT_ID: {{ .microsoftTenantId | b64enc | quote }}
  {{- end }}
  {{- if .microsoftRedirectUrl }}
  MICROSOFT_REDIRECT_URI: {{ .microsoftRedirectUrl | b64enc | quote }}
  {{- end }}
  {{- if .atlassianClientId }}
  ATLASSIAN_CLIENT_ID: {{ .atlassianClientId | b64enc | quote }}
  {{- end }}
  {{- if .atlassianClientSecret }}
  ATLASSIAN_CLIENT_SECRET: {{ .atlassianClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .atlassianRedirectUrl }}
  ATLASSIAN_REDIRECT_URL: {{ .atlassianRedirectUrl | b64enc | quote }}
  {{- end }}
  {{- if .gcsServiceAccountCredentials }}
  GCS_SERVICE_ACCOUNT_BASE64: {{ .gcsServiceAccountCredentials | b64enc | quote }}
  {{- end }}
  {{- end }}