metadata:
  slug: 'open-webui'
  name: 'Open WebUI'
  description: 'Open WebUI is a web user interface for managing Kubernetes.'
  logoUrlDark: 'http://localhost:8080/logos/addons/open-webui-small.svg' # TODO
  logoUrlLight: 'http://localhost:8080/logos/addons/open-webui-small.svg' # TODO
  detailUrl: https://nh-addons.netlify.app/open-webui
  externalUrl: 'https://helm.openwebui.com/'
  installTargets:
    hub: true
    hubRequired: true
    edge: false

forms: 
  - slug: defaultO
    label: 'Open WebUI configuration'
    description: 'Something cool to say about it, maybe'
    steps:
      - slug: 'models'
        variableSlugs:
        - 'modelsToPull'
        - 'gpuEnabled'
        ui:
          label: 'Models'  
variables:
  - slug: 'modelsToPull'
    name: 'LLM Models to Pull'
    path: 'open-webui.ollama.ollama.models.pull'
    forms: ['default']
    ui:
      # TODO: change text to list
      type: 'text'
      placeholder: 'Models to pull from: https://ollama.com/search'
      validation: 'required'
  - slug: 'gpuEnabled'
    name: 'GPU Enabled'
    path: 'open-webui.ollama.ollama.gpu'
    forms: ['default']
    ui:
      type: 'boolean'
      placeholder: 'Use GPU'
system:
  - path: 'open-webui.ingress.host'
    value: 'chat.${system.hubCluster.ingressHostname}'
    