{{- if not .Values.opencost.opencost.cloudIntegrationSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- with .Values.cloudIntegrationSecret.metadata }}
metadata: {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.cloudIntegrationSecret.spec }}
spec: {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
