{{- if not .Values.cloud-integration-secret.existingSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- with .Values.cloud-integration-secret.metadata }}
metadata: {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.cloud-integration-secret.spec }}
spec: {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
