metadata:
  slug: "oauth2-proxy"
  name: "oAuth2 Proxy"
  description: "oAuth2 Proxy is a reverse proxy and static file server that provides authentication using Providers (Google, GitHub, and others) to validate accounts by email, domain or group."
  categories: ["Security"]
  logoUrlDark: "https://avatars.githubusercontent.com/u/62798169?s=200&v=4"
  logoUrlLight: "https://avatars.githubusercontent.com/u/62798169?s=200&v=4"
  detailUrl: "https://addons.kaops.net/oauth2-proxy/"
  externalUrl: "https://oauth2-proxy.github.io/oauth2-proxy/"
  isProduction: false
  installTargets:
    hub: true
    hubRequired: false
    edge: false

forms:
  - slug: default
    label: "oAuth2 Proxy configuration"
    description: "Something cool to say about it, maybe"

variables:
  - slug: "clientId"
    path: "oauth2-proxy.config.clientID"
    forms: ["default"]
    ui:
      type: "text"
      label: "Oauth Client ID"
  - slug: "clientSecret"
    path: "oauth2-proxy.config.clientSecret"
    forms: ["default"]
    ui:
      type: "password" #TODO: Change to secret
      label: "Oauth Client Secret"
  - slug: "cookieSecret"
    path: "oauth2-proxy.config.cookieSecret"
    forms: ["default"]
    ui:
      type: "password" #TODO: Change to secret
      label: "Oauth Cookie Secret"
  - slug: "oidcConfig"
    path: "oauth2-proxy.config.configFile"
    forms: ["default"]
    ui:
      type: "text"
      label: "OIDC Configuration"

system:
  - path: "oauth2-proxy.ingress.hosts[0].host"
    value: "${system.hubCluster.ingressHostname}"
  - path: "oauth2-proxy.ingress.hosts[0].paths[0].path"
    value: "/oauth"
  - path: "oauth2-proxy.ingress.hosts[0].paths[0].pathType"
    value: "Prefix"
  - path: "oauth2-proxy.ingress.tls[0].hosts[0]"
    value: "oauth.${system.hubCluster.ingressHostname}"
  - path: "oauth2-proxy.ingress.tls[0].secretName"
    value: "oauth-tls"

output:
  - name: Test
    description: "test"
    value: "https://oauth.${system.hubCluster.ingressHostname}"
    type: "url"
    slug: default
