metadata:
  slug: "oauth2-proxy"
  name: "oAuth2 Proxy"
  description: "oAuth2 Proxy is a reverse proxy and static file server that provides authentication using Providers (Google, GitHub, and others) to validate accounts by email, domain or group."
  categories: ["Security"]
  logoUrlDark: "https://avatars.githubusercontent.com/u/62798169?s=200&v=4"
  logoUrlLight: "https://avatars.githubusercontent.com/u/62798169?s=200&v=4"
  detailUrl: "https://addons.kaops.net/oauth2-proxy/"
  externalUrl: "https://oauth2-proxy.github.io/oauth2-proxy/"
  isProduction: false
  installTargets:
    hub: true
    hubRequired: false
    edge: false

forms:
  - slug: default
    label: "oAuth2 Proxy configuration"
    description: "Something cool to say about it, maybe"

variables:
  - slug: "clientId"
    path: "oauth2-proxy.config.client_id"
    forms: ["default"]
    ui:
      type: "text"
      label: "Oauth Client ID"
  - slug: "clientSecret"
    path: "oauth2-proxy.config.client_secret"
    forms: ["default"]
    ui:
      type: "password" #TODO: Change to secret
      label: "Oauth Client Secret"
  - slug: "redirectURL"
    path: "oauth2-proxy.config.redirect_url"
    forms: ["default"]
    ui:
      type: "text"
      label: "Oauth Redirect Url"
  - slug: "scope"
    path: "oauth2-proxy.config.scope"
    forms: ["default"]
    ui:
      type: "text"
      label: "Oauth Claims Scope"
  - slug: "cookieSecret"
    path: "oauth2-proxy.config.cookie_secret"
    forms: ["default"]
    ui:
      type: "password" #TODO: Change to secret
      label: "Oauth Cookie Secret"
  - slug: "provider"
    path: "oauth2-proxy.config.provider"
    forms: ["default"]
    ui:
      type: "text"
      label: "Oauth Provider"
  - slug: "oidcIssuerUrl"
    path: "oauth2-proxy.config.oidc_issuer_url"
    forms: ["default"]
    ui:
      type: "text"
      label: "Oauth OIDC Issuer URl"
  - slug: "skip_provider_button"
    path: "oauth2-proxy.config.skip_provider_button"
    forms: ["default"]
    ui:
      type: "toggle"
      label: "Oauth Skip Provider Button"

system:
  - path: "oauth2-proxy.ingress.hosts[0]"
    value: "*.${system.hubCluster.ingressHostname}"
  - path: "oauth2-proxy.ingress.tls[0].hosts[0]"
    value: "*.${system.hubCluster.ingressHostname}"
  - path: "oauth2-proxy.ingress.tls[0].secretName"
    value: "oauth-tls"

output:
  - name: Test
    description: "test"
    value: "https://oauth.${system.hubCluster.ingressHostname}"
    type: "url"
    slug: default
