oauth2-proxy:
  config:
    client_id:
    client_secret:
    cookie_secret:
    email_domains: "*"
    oidc_issuer_url:
    pass_access_token: true
    provider:
    provider_display_name:
    redirect_url:
    scope:
    skip_provider_button:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: http
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/tls-acme: "true"
    hosts:
    tls:
      - hosts:
        secretName:
