oauth2-proxy:
  config:
    client_id: 0oantjiyd6m1P04jT5d7
    client_secret: NKKL2wx4LIbF6HMHw6EFxu0ypMr8ei1t5etRxfp9a9FCoLhQTe90sl7pBtmsI0m3
    cookie_secret: +j8qHoNVzvmAwYmJCnmA73EGc16rgz1gFPDucrUyAcY=
    email_domains: "*"
    oidc_issuer_url: https://dev-26501363-admin.okta.com
    pass_access_token: true
    provider: oidc
    provider_display_name: okta
    redirect_url: https://chat.gcp.sobczyk.dev/
    scope: openid profile email
    skip_provider_button: true
    upstreams:
      - https://chat.gcp.sobczyk.dev/
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: http
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/tls-acme: "true"
    hosts:
    tls:
      - hosts:
        secretName:
