apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ system.hubCluster.name }}-opencost
  namespace: {{ system.hubCluster.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ system.cluster.namespace }}
    server: {{ system.cluster.url}}
  source:
    path: ''
    repoURL: 'https://opencost.github.io/opencost-helm-chart'
    targetRevision: 1.43.2
    chart: opencost
  project: nethopper-feature #TODO: create a new project for kaops blueprints
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s