forms: 
  - name: "myform"
    description: "Form for namespace"
    type: standard
  - name: "secrets"
    type: secret
  
variables:
  - name: "metadata.namespace"
    description: "Namespace where the application will be deployed"
    form: "myform"
    formKitSchema: ""
    type: "text"
    label: "Namespace"
    required: true
  - name: "pearSecret"
    description: "Secret for pear"
    form: "secrets"
    type: "secret"
    label: "Pear Secret"
    required: true