forms: 
  - name: "myform"
    description: "Form for namespace"
    type: standard
  - name: "myform"
    type: secret
  
variables:
  - name: "eksRoleArn"
    description: "Role ARN for EKS"
    form: "myform"
    type: "text"
    label: "EKS Role ARN"
    required: true
  # - name: "metadata.namespace"
  #   description: "Namespace where the application will be deployed"
  #   form: "myform"
  #   formKitSchema: ""
  #   type: "text"
  #   label: "Namespace"
  #   required: true
  # - name: "pearSecret"
  #   description: "Secret for pear"
  #   form: "secrets"
  #   type: "secret"
  #   label: "Pear Secret"
  #   required: true
