metadata:
  slug: beatles
  name: Beatles
  description: One of the most successful and influential bands in the history of popular music.
  logoUrlDark: "https://nh-addons.s3.us-east-1.amazonaws.com/beatles/logo.png"
  logoUrlLight: "https://nh-addons.s3.us-east-1.amazonaws.com/beatles/logo.png"
  detailUrl: "https://addons.kaops.net/beatles/"
  externalUrl: "https://github.com/golang-samples/gopher-vector?tab=readme-ov-file"
  installTargets:
    infoMessage: Innovative songwriting, vocal harmonies, and groundbreaking recordings

forms:
  - slug: default
    label: Configuration
    steps:
      - slug: details
        isCreateOnly: true
        variableSlugs:
          - ssoEnabled
        ui:
          label: Details
  - slug: defaultUpdate
    label: Configuration
variables:
  - slug: ssoEnabled
    path: ingress.oauth2Proxy.enabled
    forms: [default, defaultUpdate]
    ui:
      type: toggle
      label: Use Single Sign On
      id: ssoEnabled
      value: false
  - slug: ssoEnabledDependencies
    path: open-webui.extraEnvVars
    isStatic: true
    forms: [default]
    ui:
      type: list
      children:
        - if: $get(ssoEnabled).value
          type: group
          name: extraEnvVars
          children:
            - type: hidden
              name: name
              value: WEBUI_AUTH
            - type: hidden
              name: value
              value: false
          else:
            type: group
            name: extraEnvVars
            children:
              - type: hidden
                name: name
                value: WEBUI_AUTH
              - type: hidden
                name: value
                value: true

system:
  - path: open-webui.ingress.host
    value: "chat.${system.hubCluster.ingressHostname}"
