apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  labels:
    app: oauth2
data:
  oauth2_proxy.cfg: |-
    clientId: "{{ .Values.oauth2-configmap.clientId }}"
    clientSecret: "{{ .Values.oauth2-configmap.clientSecret }}"
    cookieSecret: "{{ .Values.oauth2-configmap.cookieSecret }}"
    email_domains: "{{ .Values.oauth2-configmap.email_domains }}"
    oidc_issuer_url: "{{ .Values.oauth2-configmap.oidc_issuer_url }}"
    pass_access_token: "{{ .Values.oauth2-configmap.pass_access_token }}"
    pass_user_headers: "{{ .Values.oauth2-configmap.pass_user_headers }}"
    pass_host_header: "{{ .Values.oauth2-configmap.pass_host_header }}"
    pass_authorization_header: "{{ .Values.oauth2-configmap.pass_authorization_header }}"
    set_xauthrequest: "{{ .Values.oauth2-configmap.set_xauthrequest }}"
    skip_provider_button: "{{ .Values.oauth2-configmap.skip_provider_button }}"
    provider: "{{ .Values.oauth2-configmap.provider }}"
    provider_display_name: "{{ .Values.oauth2-configmap.provider_display_name }}"
    redirect_url: "{{ .Values.oauth2-configmap.redirect_url }}"
    upstreams: "{{ .Values.oauth2-configmap.upstreams }}"
    whitelist_domains: "{{ .Values.oauth2-configmap.whitelist_domains }}"
    cookie_domains: "{{ .Values.oauth2-configmap.cookie_domains }}"
    cookie_expire: "{{ .Values.oauth2-configmap.cookie_expire }}"
    cookie_name: "{{ .Values.oauth2-configmap.cookie_name }}"
    upstream_timeout: "{{ .Values.oauth2-configmap.upstream_timeout }}"
    reverse_proxy: "{{ .Values.oauth2-configmap.reverse_proxy }}"
    scope: "{{ .Values.oauth2-configmap.scope }}"
