{{- $randomPassword := randAlphaNum 16 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets-rag
  labels:
    {{- include "nh-intel.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.secretArgocdHook }}
data:
  JWT_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  DATABASE_URL: {{ (print "postgresql://" .Values.global.postgresql.auth.username ":" $randomPassword "@" .Values.rag.postgresHost ":5432/postgres") | b64enc | quote }}
  POSTGRES_CREDENTIALS: {{ $randomPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  labels:
    {{- include "nh-intel.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.secretArgocdHook }}
data:
  postgresPassword: {{ $randomPassword | b64enc | quote }}
