metadata:
  slug: 'hello-go'
  name: 'Hello Go'
  description: 'A Hello World application written in the Go language. No input parameters.'
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/hello-go/logo.png'
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/hello-go/logo.png'
  detailUrl: 'https://addons.kaops.net/hello-go/'
  externalUrl: 'https://github.com/golang-samples/gopher-vector?tab=readme-ov-file'
  installTargets:
    hub: true
    hubRequired: true
    edge: false
    clusterMessage: Enter cluster restrictions and requirements here. Must be installed on clusters configured for Ingress.
    infoMessage: Info message
    warningMessage: The Frontend UX displays this text as an warning message in the cluster Addon config dialog.

forms:
  - slug: default
    label: Configuration
    steps:
      - slug: details
        isCreateOnly: true
        variableSlugs:
          - ssoEnabled
          - gpuEnabled
          - modelsToPull
        ui:
          label: Details
      - slug: postInstall
        isCreateOnly: true
        variableSlugs:
          - postInstallOptions
        ui:
          label: Options
#      - slug: sso
##        variableSlugs:
##          - TODO
#        ui:
#          # TODO: This step must show in update mode if sso was configured
#          if: $u.includes($get(postInstallOptions).value, 'sso')
#          label: SSO
      - slug: groups
        isCreateOnly: true
        variableSlugs:
          - postInstallGroups
        ui:
          if: $u.includes($get(postInstallOptions).value, 'groups')
          label: Groups
      - slug: knowledge
        isCreateOnly: true
        variableSlugs:
          - postInstallKnowledgeBases
        ui:
#          if: "$u.includes($get(postInstallOptions).value, 'knowledge') && $get(postInstallGroups).value.length > 0"
          if: "$u.includes($get(postInstallOptions).value, 'knowledge')"
          label: Knowledge
variables:
  - slug: ssoEnabled
    path: open-webui.oauth2Proxy.enabled
    forms: [ default ]
    ui:
      type: toggle
      label: Use Single Sign On
  - slug: gpuEnabled
    path: open-webui.ollama.ollama.gpu.enabled
    forms: [default]
    ui:
      type: toggle
      label: Use GPU
  - slug: modelsToPull
    path: open-webui.ollama.ollama.models.pull
    forms: [default]
    ui:
      type: transferlist
      label: Select LLM Models to Pull
      sourceLabel: LLM Models
      options: [gemma2, gemma3:1b, gemma3:4b, llama3.1:8b, llama3.2:3b]
      help: 'Models to pull from: https://ollama.com/search'
      searchable: true
  - slug: postInstallOptions
    path: _postInstall.chosenPostInstallOptions
    forms: [default]
    ui:
      type: checkbox
      options:
        - label: Use Single Sign-On
          value: sso
        - label: Select Suggested Groups
          value: groups
        - label: Provide Knowledge Containers
          value: knowledge
      value:
        - groups
        - knowledge
  - slug: postInstallGroups
    path: _postInstall.groups
    forms: [default]
    ui:
      type: transferlist
      label: Groups
      help: The installation process will automatically create the selected groups. You can change the names & details anytime inside the application itself.
      options:
        - label: Engineering Team
          value:
            name: Engineering Team
            description: A group for software engineers
        - label: Product Management
          value:
            name: Product Management
            description: A group for product managers
        - label: Marketing Team
          value:
            name: Marketing Team
            description: A group for marketing professionals
        - label: Customer Support
          value:
            name: Customer Support
            description: A group for customer support representatives
      value:
        - name: Engineering Team
          description: A group for software engineers
        - name: Product Management
          description: A group for product managers
        - name: Marketing Team
          description: A group for marketing professionals
        - name: Customer Support
          description: A group for customer support representatives
      validation: 'required'
  - slug: postInstallKnowledgeBases
    path: _postInstall.knowledgeBases
    forms: [default]
    ui:
      type: repeater
      label: Knowledge Bases
      key: "$: 'knowledgeBases-' + $get(postInstallGroups).value.length"
      addButton: false
      insertControl: true
      upControl: false
      downControl: false
      help: The installation process will automatically create these knowledge bases. You can change the names & details anytime inside the application itself.
      children:
        - label: What are you working on?
          type: text
          name: name
          help: Name your knowledge base
          validation: required
        - label: What are you trying to achieve?
          type: text
          name: description
          help: Describe your knowledge base and objectives
          validation: required
#        - label: Groups
#          type: transferlist
#          name: groups
#          options: $u.map($get(postInstallGroups).value, 'name')
        - label: Groups
          type: taglist
          name: groups
          key: "$: 'knowledgeBaseGroups-' + $get(postInstallGroups).value.length"
          options: $u.map($get(postInstallGroups).value, 'name')
          disableDragAndDrop: true
          allowNewValues: true
          popover: true
          openOnClick: true
          closeOnSelect: false
          help: Select groups with write access to this knowledge base
          # pre-select the related group for each knowledge base (if the group was chosen)
          value:
            if: "$value.name == 'Best Practices for Code Reviews' && $u.find($get(postInstallGroups).value, $u.matchesProperty('name', 'Engineering Team'))"
            then: ['Engineering Team']
            else:
              if: "$value.name == 'Social Media Strategy For This Year' && $u.find($get(postInstallGroups).value, $u.matchesProperty('name', 'Marketing Team'))"
              then: ['Marketing Team']
              else:
                if: "$value.name == 'Agile Project Management Tips' && $u.find($get(postInstallGroups).value, $u.matchesProperty('name', 'Product Management'))"
                then: ['Product Management']
                else:
                  if: "$value.name == 'Handling Difficult Customers' && $u.find($get(postInstallGroups).value, $u.matchesProperty('name', 'Customer Support'))"
                  then: ['Customer Support']
                  else: []
      value:
        - name: Best Practices for Code Reviews
          description: This guide outlines the key steps for effective code reviews.
        - name: Social Media Strategy For This Year
          description: An overview of our social media approach for the upcoming year.
        - name: Agile Project Management Tips
          description: Key insights for managing agile projects effectively.
        - name: Handling Difficult Customers
          description: Techniques and strategies for resolving challenging customer situations.

system:
  - path: open-webui.ingress.host
    value: 'chat.${system.hubCluster.ingressHostname}'

output:
  - name: Open Web UI URL
    description: The URL to access Open WebUI
    value: 'https://chat.${system.hubCluster.ingressHostname}'
    type: url
    slug: default

# old junk below
#forms:
#  - slug: default
#    label: 'Hello world app'
#    steps:
#      - slug: one
#        variableSlugs:
#          - hello
#        ui:
#          label: One
#      - slug: two
#        variableSlugs:
#          - item1
#        ui:
#          label: Two
#        isCreateOnly: true
#  - slug: foo
#    label: Foo Form
#    caption: A form caption
#    isFormOption: true
#  - slug: bar
#    label: Bar Form
#  - slug: baz
#    label: Baz Form
#    isFormOption: true
#    isCreateOnly: true
#
#variables:
#  - slug: 'hello'
#    path: 'hello'
#    forms: ['default']
#    ui:
#      type: 'text'
#      label: 'Hello'
#  - slug: 'bye'
#    path: 'bye'
#    forms: ['foo']
#    ui:
#      type: 'text'
#      label: 'Bye Foo'
#  - slug: 'bazzercise'
#    path: 'bazzercise'
#    forms: ['baz']
#    ui:
#      type: 'text'
#      label: 'Baz!'
#  - slug: 'item1'
#    path: 'item1'
#    forms: ['default']
#    ui:
#      type: 'radio'
#      label: 'Show item 2?'
#      options:
#        - label: Yes
#          value: true
#        - label: No
#          value: false
#      value: true
#  - slug: 'item2'
#    path: 'item2'
#    forms: ['default']
#    ui:
#      if: '$get(item1).value'
#      type: 'text'
#      label: 'Item 2'

