metadata:
  slug: 'hello-go'
  name: 'Hello Go'
  description: 'A Hello World application written in the Go language. No input parameters.'
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/hello-go/logo.png'
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/hello-go/logo.png'
  detailUrl: 'https://addons.kaops.net/hello-go/'
  externalUrl: 'https://github.com/golang-samples/gopher-vector?tab=readme-ov-file'
  installTargets:
    hub: true
    hubRequired: true
    edge: false
    clusterMessage: Enter cluster restrictions and requirements here. Must be installed on clusters configured for Ingress.
    infoMessage: Info message
    warningMessage: The Frontend UX displays this text as an warning message in the cluster Addon config dialog.

forms: 
  - slug: default
    label: 'Hello world app'
variables:
  - slug: 'hello'
    path: 'hello'
    forms: ['default']
    ui:
      type: 'text'
      label: 'Hello'
  - slug: 'item1'
    path: 'item1'
    forms: ['default']
    ui:
      type: 'radio'
      label: 'Show item 2?'
      options:
        - label: Yes
          value: true
        - label: No
          value: false
      value: true
  - slug: 'item2'
    path: 'item2'
    forms: ['default']
    ui:
      if: '$get(item1).value'
      type: 'text'
      label: 'Item 2'
    
