metadata:
  slug: 'hello-go'
  name: 'Hello Go'
  description: 'A Hello World application written in the Go language. No input parameters.'
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/hello-go/logo.png'
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/hello-go/logo.png'
  detailUrl: 'https://addons.kaops.net/hello-go/'
  externalUrl: 'https://github.com/golang-samples/gopher-vector?tab=readme-ov-file'
  installTargets:
    hub: true
    hubRequired: true
    edge: false
    clusterRestrictions: 'Must be installed on clusters configured for Ingress.  This is an extra-long set of requirements to test the UX.'

forms: 
  - slug: default
    label: 'Hello worl app '
    description: 'Something cool to say about it, maybe'
    # steps:
    #   - slug: 'hello'
    #     variableSlugs:
    #     - 'name'
    #     ui:
    #       label: 'Hello'  
variables:
  - slug: 'hello'
    name: 'hello'
    path: 'hello'
    forms: ['hello']
    ui:
      type: 'text'
      label: 'Hello'
    
