apiVersion: v2
name: nh-ai-benchmark
description: KAOPS addon to install NH AI Benchmark (API + UI)
type: application
version: 0.1.3
appVersion: "0.1.0"

dependencies:
  - name: nh-ai-benchmark
    version: 0.1.1
    repository: https://nethopper2.github.io/helm-charts/
    condition: nh-ai-benchmark.enabled
