{{- if and .Values.camel-k.enabled .Values.camel-k.integrations.gdrivegcs.enabled }}
{{- if .Values.camel-k.integrations.gdrivegcs.googleCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gdrivegcs-credentials
  namespace: {{ .Values.camel-k.operator.watchNamespace }}
  labels:
    app: {{ .Release.Name }}
    integration: gdrivegcs
type: Opaque
data:
  google-credentials.json: {{ .Values.camel-k.integrations.gdrivegcs.googleCredentialsSecret | quote }}
{{- end }}
{{- end }}
