{{- if .Values.camel-k.platform.enabled }}
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: {{ .Values.camel-k.platform.name }}
  namespace: {{ .Values.camel-k.operator.namespace }}
  labels:
    {{- include "camel-k.labels" . | nindent 4 }}
spec:
  profile: {{ .Values.camel-k.platform.profile }}
  {{- if .Values.camel-k.platform.build }}
  build:
    {{- if .Values.camel-k.platform.build.strategy }}
    strategy: {{ .Values.camel-k.platform.build.strategy }}
    {{- end }}
    {{- if .Values.camel-k.platform.build.timeout }}
    timeout: {{ .Values.camel-k.platform.build.timeout }}
    {{- end }}
    {{- if .Values.camel-k.platform.build.maven }}
    maven:
      {{- toYaml .Values.camel-k.platform.build.maven | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.camel-k.registry.enabled }}
  build:
    registry:
      address: {{ .Values.camel-k.registry.address }}
      {{- if .Values.camel-k.registry.secret }}
      secret: {{ .Values.camel-k.registry.secret }}
      {{- end }}
      {{- if .Values.camel-k.registry.organization }}
      organization: {{ .Values.camel-k.registry.organization }}
      {{- end }}
      {{- if .Values.camel-k.registry.insecure }}
      insecure: {{ .Values.camel-k.registry.insecure }}
      {{- end }}
  {{- end }}
  {{- if .Values.camel-k.platform.traits }}
  traits:
    {{- toYaml .Values.camel-k.platform.traits | nindent 4 }}
  {{- end }}
  {{- end }}
