{{- if and .Values.camel-k.monitoring.prometheus.enabled .Values.camel-k.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "camel-k.fullname" . }}
  namespace: {{ default .Values.camel-k.operator.namespace .Values.camel-k.monitoring.prometheus.serviceMonitor.namespace }}
  labels:
    {{- include "camel-k.labels" . | nindent 4 }}
      {{- with .Values.camel-k.monitoring.prometheus.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "camel-k.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  {{- end }}
