metadata:
  slug: camel-k-gdrive-gcs-sync
  name: Camel K Google Drive to GCS Sync
  description: Synchronize files from Google Drive to Google Cloud Storage using Apache Camel K
  categories: [Integration, Storage]
  logoUrlDark: "https://nh-addons.s3.us-east-1.amazonaws.com/camel-k-gdrive-gcs-sync/logo-dark.png"
  logoUrlLight: "https://nh-addons.s3.us-east-1.amazonaws.com/camel-k-gdrive-gcs-sync/logo-light.png"
  detailUrl: "https://addons.kaops.net/camel-k-gdrive-gcs-sync/"
  externalUrl: "https://camel.apache.org/camel-k/"
  isProduction: false
  isStaging: false
  useSafeDelete: true
  installTargets:
    clusterMessage: Must be installed on clusters with Camel K operator already running.
    infoMessage: This addon requires the Camel K addon to be installed first.

forms:
  - slug: default
    label: Configuration
    steps:
      - slug: basic
        variableSlugs:
          - googleCredentialsSecret
          - gcsBucketName
          - allowedFileExtensions
        ui:
          label: Basic
      - slug: advanced
        variableSlugs:
          - idempotencyEnabled
          - idempotencyRepository
          - idempotencyExpiration
          - camelReplicas
        ui:
          label: Advanced

variables:

  - slug: googleCredentialsSecret
    path: googleCredentialsSecret
    forms: [default]
    ui:
      type: secret
      label: Google Credentials
      help: Google service account credentials JSON file with access to Google Drive and GCS (will be automatically base64-encoded)
      validation: required

  - slug: gcsBucketName
    path: gcsBucketName
    forms: [default]
    ui:
      type: text
      label: GCS Bucket Name
      help: Name of the Google Cloud Storage bucket to store files
      validation: required

  - slug: allowedFileExtensions
    path: allowedFileExtensions
    forms: [default]
    ui:
      type: taglist
      label: Allowed File Extensions
      help: File extensions to sync (e.g. .pdf) If not provided, ALL files will be synced!
      popover: true
      allowNewValues: true

  # Advanced settings

  # Advanced settings
  - slug: idempotencyEnabled
    path: idempotency.enabled
    forms: [default]
    ui:
      type: toggle
      label: Enable Idempotency
      id: idempotencyEnabled
      value: true
      help: Prevent concurrent syncs for the same user

  - slug: idempotencyRepository
    path: idempotency.repository
    forms: [default]
    ui:
      if: $get(idempotencyEnabled).value
      type: select
      label: Idempotency Repository
      help: Storage type for tracking sync operations
      value: memory
      options:
        - value: "memory"
          label: "In-Memory (not persistent)"
        - value: "redis"
          label: "Redis (automatically uses shared Redis configuration)"



  - slug: idempotencyExpiration
    path: idempotency.expiration
    forms: [default]
    ui:
      if: $get(idempotencyEnabled).value
      type: number
      label: Idempotency Lock Time (ms)
      help: Time in milliseconds to prevent duplicate sync operations
      value: 600000
      min: 30000
      max: 3600000

  - slug: camelReplicas
    path: camelK.replicas
    forms: [default]
    ui:
      type: number
      label: Number of Replicas
      help: Number of integration instances to run
      value: 2
      min: 1
      max: 10

system:
  - path: "camelK.namespace"
    value: "${system.cluster.namespace}"
  - path: "camelK.watchNamespace"
    value: "${system.cluster.namespace}"

output:
  - name: API Endpoint
    description: API Endpoint for triggering Google Drive sync
    value: "http://{{ .Release.Name }}-gdrivegcs-api.${system.cluster.namespace}.svc.cluster.local:8080/sync/gdrive"
    type: string
    slug: default

  - name: Integration Status
    description: Check the status of the Google Drive to GCS API integration
    value: "kubectl get integration gdrivegcs-api -n ${system.cluster.namespace}"
    type: command
    slug: default

  - name: Integration Logs
    description: View the Google Drive to GCS API logs
    value: "kubectl logs -l integration=gdrivegcs-api -n ${system.cluster.namespace} -f"
    type: command
    slug: default

  - name: Sample Curl Command
    description: Example curl command to trigger a sync (replace values in <>)
    value: |
      curl -X POST \
        "http://{{ .Release.Name }}-gdrivegcs-api.${system.cluster.namespace}.svc.cluster.local:8080/sync/gdrive" \
        -H "Content-Type: application/json" \
        -d '{
          "userId": "<USER_ID>",
          "accessToken": "<GOOGLE_ACCESS_TOKEN>",
          "refreshToken": "<GOOGLE_REFRESH_TOKEN>",
          "allowedExtensions": "pdf,docx,xlsx"
        }'
    # Note: Files will automatically be stored in "user-<USER_ID>" folder in the GCS bucket
    type: string
    slug: default

dependencies:
  addons:
    - slug: 'camel-k'
      name: 'Apache Camel K'
      required: true
    - slug: 'redis'
      name: 'Redis'
      required: false
      description: 'Recommended when using Redis as idempotency repository'
