apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-dependency-check
  namespace: {{ .Values.camelK.watchNamespace }}
  labels:
    app: {{ .Release.Name }}
    integration: gdrivegcs
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}-dependency-check
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      restartPolicy: Never
      containers:
      - name: dependency-check
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Checking for Camel K operator..."

          # Check if Camel K operator is running in the namespace
          OPERATOR_NS="{{ .Values.camelK.namespace }}"
          if kubectl get deployment -n "$OPERATOR_NS" | grep camel-k-operator >/dev/null 2>&1; then
            echo "Found Camel K operator in namespace '$OPERATOR_NS'."
          else
            echo "WARN: Could not find Camel K operator in namespace '$OPERATOR_NS'."
            echo "Proceeding anyway, but integration may not work correctly."
          fi

          # Check for some Camel K resources
          if kubectl get integrations -n "$OPERATOR_NS" >/dev/null 2>&1; then
            echo "Integration API appears to be working."
          else
            echo "WARN: Could not access Integration API in namespace '$OPERATOR_NS'."
            echo "Proceeding anyway, but ensure Camel K is properly installed."
          fi

          echo "Dependency check complete."
          exit 0
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
