apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-dependency-check
  namespace: {{ .Values.camelK.watchNamespace }}
  labels:
    app: {{ .Release.Name }}
    component: dependency-check
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: dependency-check
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
        - name: check-dependencies
          image: bitnami/kubectl:latest
          command:
            - "sh"
            - "-c"
            - |
              # Check if Camel K CRDs exist
              if ! kubectl get crd kamelets.camel.apache.org > /dev/null 2>&1; then
                echo "ERROR: Camel K CRDs not found. Please install the Camel K addon first."
                exit 1
              fi

              # Check if Camel K operator is running
              if ! kubectl get deployment -n {{ .Values.camelK.namespace }} camel-k-operator > /dev/null 2>&1; then
                echo "ERROR: Camel K operator not found in namespace {{ .Values.camelK.namespace }}."
                exit 1
              fi

              echo "Camel K dependencies verified successfully."
              exit 0
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
  backoffLimit: 1
