{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gdrivegcs-config
  namespace: {{ .Values.camelK.watchNamespace }}
  labels:
    app: {{ .Release.Name }}
    component: gdrivegcs
data:
  # GCS bucket name for file storage
  GCS_BUCKET_NAME: "{{ .Values.gcsBucketName }}"

  # Endpoint information
  API_ENDPOINT_PATH: "{{ .Values.endpoint.path }}"
  API_ENDPOINT_PORT: "{{ .Values.endpoint.port }}"

  # Idempotency settings (used by the integration)
  IDEMPOTENCY_ENABLED: "{{ .Values.idempotency.enabled }}"
  IDEMPOTENCY_REPOSITORY: "{{ .Values.idempotency.repository }}"
  IDEMPOTENCY_EXPIRATION: "{{ .Values.idempotency.expiration }}"
{{- end }}
