{{- if .Values.googleCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gdrivegcs-credentials
  namespace: {{ .Values.camelK.namespace }}
  labels:
    app: {{ .Release.Name }}
    integration: gdrivegcs
type: Opaque
data:
  # Service account credentials for GCS bucket access
  google-credentials.json: {{ .Values.googleCredentialsSecret | quote }}
{{- end }}
