{{- if .Values.enabled }}
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: gdrivegcs-sync
  namespace: {{ .Values.camelK.watchNamespace }}
  labels:
    app: {{ .Release.Name }}
    integration: gdrivegcs
spec:
  replicas: 1
  traits:
    mount:
      volumes:
      - name: google-credentials
        secret:
          secretName: {{ .Release.Name }}-gdrivegcs-credentials
      mounts:
      - name: google-credentials
        path: /etc/google-credentials
  sources:
    - name: "gdrivegcs-sync.js"
      content: |
{{ (.Files.Get "scripts/gdrivegcs-sync.js") |
   replace "__ALLOWED_EXTENSIONS__" (.Values.allowedFileExtensions | default "") |
   replace "__SYNC_INTERVAL_SECONDS__" (.Values.syncIntervalSeconds | default 3600 | toString) |
   replace "__GCS_BUCKET_NAME__" .Values.gcsBucketName |
   indent 8 }}

{{- end }}
