{{- if .Values.googleCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gdrivegcs-credentials
  namespace: {{ .Values.camelK.namespace }}
  labels:
    app: {{ .Release.Name }}
    integration: gdrivegcs
type: Opaque
stringData:
  # Service account credentials for GCS bucket access - NOT base64 encoded
  google-credentials.json: |
    {{ .Values.googleCredentialsSecret | b64dec }}
{{- end }}
