{{- if .Values.enabled }}
{{- if .Values.googleCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gdrivegcs-credentials
  namespace: {{ .Values.camelK.watchNamespace }}
  labels:
    app: {{ .Release.Name }}
    integration: gdrivegcs
type: Opaque
data:
  google-credentials.json: {{ .Values.googleCredentialsSecret | quote }}
{{- end }}
{{- end }}
