apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: user-gcs-sink
  namespace: {{ .Values.camelK.watchNamespace }}
  labels:
    app: {{ .Release.Name }}
    integration: gdrivegcs
spec:
  definition:
    title: "User Google Cloud Storage Sink"
    description: "Store files in Google Cloud Storage with user-specific paths"
    required:
      - bucketName
    properties:
      bucketName:
        title: GCS Bucket Name
        description: Name of the Google Cloud Storage bucket
        type: string
      credentialsPath:
        title: Credentials Path
        description: Path to the Google credentials file
        type: string
        default: "/etc/google-credentials/google-credentials.json"
      userFolder:
        title: User Folder
        description: Optional subfolder within bucket to store user files
        type: string
        default: ""
  template:
    from:
      uri: "direct:gcs-sink"
      steps:
        # Set GCS headers for the file upload
        - setHeader:
            name: "CamelGoogleStorage.bucketName"
            simple: "${header.bucketName}"
        - setHeader:
            name: "CamelGoogleStorage.serviceAccountKey"
            simple: "${header.credentialsPath}"
        # Determine object name (with user folder if specified)
        - choice:
            when:
              - simple: "${header.userFolder} != ''"
              - setHeader:
                  name: "CamelGoogleStorage.objectName"
                  simple: "${header.userFolder}/${header.fileName}"
            otherwise:
              - setHeader:
                  name: "CamelGoogleStorage.objectName"
                  simple: "${header.fileName}"
        # Upload to GCS
        - to: "google-storage:{{`{{header.bucketName}}`}}"
        # Log successful upload
        - log:
            message: "Uploaded ${header.fileName} to GCS bucket: ${header.bucketName}"
