apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Values.camelK.namespace }}
  labels:
    app: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-kamelet-role
  namespace: {{ .Values.camelK.namespace }}
  labels:
    app: {{ .Release.Name }}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: ["camel.apache.org"]
  resources: ["kamelets", "integrations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "services", "pods", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-kamelet-role-binding
  namespace: {{ .Values.camelK.namespace }}
  labels:
    app: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-sa
  namespace: {{ .Values.camelK.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-kamelet-role
  apiGroup: rbac.authorization.k8s.io
