open-webui:
  ollama:
    ollama:
      gpu:
        enabled: false
      models:
        pull: []
    service:
      type: ClusterIP
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
      nginx.ingress.kubernetes.io/backend-protocol: http
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/tls-acme: 'true'
    host:
    tls: true
    existingSecret: "webui-tls"
  extraEnvVars:
    - name: WEBUI_NAME
      value: 'SWAY.IO'
    - name: WEBUI_TITLE
      value: 'Sway.io'
    - name: WEBUI_FAVICON
      value: 'https://sway.io/favicon.ico'
    - name: WEBUI_LOGO
      value: 'https://sway.io/logo.png'
