camel-k:
  enabled: true

  # These values will be passed directly to the upstream chart
  operator:
    namespace: nh-addons
    logLevel: info
    env:
      # Disable kamelets due to K8s 1.32 schema compatibility
      - name: KAMEL_INSTALL_DEFAULT_KAMELETS
        value: "false"

  # Platform configuration
  platform:
    profile: Kubernetes

  monitoring:
    enabled: false
