camel-k:
  enabled: true

  integrations:
    gdrivegcs:
      enabled: false
      googleCredentialsSecret: ""
      gcsBucketName: ""
      allowedFileExtensions: "pdf,docx,txt,xlsx,pptx"
      syncIntervalSeconds: "3600"

  operator:
    namespace: nh-addons
    logLevel: info
    # Commenting out Kamelet-disabling env vars to re-enable Kamelets
    # env:
    #   # Disable Kamelets completely
    #   - name: KAMEL_INSTALL_DEFAULT_KAMELETS
    #     value: "false"
    #   - name: KAMEL_KAMELET_CATALOG_ENABLED
    #     value: "false"
    #   # Skip Kamelet installation entirely
    #   - name: KAMEL_KAMELET_CATALOG_REPO
    #     value: ""

  # Platform configuration - re-enable Kamelet catalog at platform level
  platform:
    profile: Kubernetes
    build:
      timeout: 5m
      # Configure registry at platform level
      registry:
        address: "docker.io"
    # Re-enable Kamelet catalog by commenting out the empty repositories
    # kamelet:
    #   repositories: []

  # Explicitly disable all monitoring and optional features
  monitoring:
    enabled: false

  # Install basic Camel K CRDs (but skip Kamelets)
  installCRDs: true
