camel-k:
  enabled: true

  # These values will be passed directly to the upstream chart
  operator:
    namespace: camel-k-system
    logLevel: info

  platform:
    enabled: true
    profile: Kubernetes

  monitoring:
    enabled: false
