camel-k:
  enabled: true

  operator:
    namespace: nh-addons
    logLevel: info
    env:
      # Disable Kamelets completely
      - name: KAMEL_INSTALL_DEFAULT_KAMELETS
        value: "false"
      - name: KAMEL_KAMELET_CATALOG_ENABLED
        value: "false"
      # Skip Kamelet installation entirely
      - name: KAMEL_KAMELET_CATALOG_REPO
        value: ""

  # Platform configuration - disable Kamelet catalog at platform level
  platform:
    profile: Kubernetes
    build:
      timeout: 5m
    # Explicitly disable Kamelet catalog
    kamelet:
      repositories: []

  # Configure registry for image building
  registry:
    address: "docker.io"
    organization: "camelk"
    # Use default registry credentials from the cluster

  # Explicitly disable all monitoring and optional features
  monitoring:
    enabled: false

  # Install basic Camel K CRDs (but skip Kamelets)
  installCRDs: true
