camel-k:
  enabled: true

  operator:
    namespace: nh-addons
    logLevel: info
    env:
      # Disable default Kamelets to resolve progressing state issue
      - name: KAMEL_INSTALL_DEFAULT_KAMELETS
        value: "false"
      - name: KAMEL_KAMELET_CATALOG_ENABLED
        value: "false"

  # Platform configuration without Kamelet catalog
  platform:
    profile: Kubernetes
    build:
      timeout: 5m
      # Configure registry at platform level
      registry:
        address: "docker.io"

  # Explicitly disable all monitoring and optional features
  monitoring:
    enabled: false

  # Install basic Camel K CRDs (but skip Kamelets)
  installCRDs: true
