camel-k:
  enabled: true

  operator:
    namespace: nh-addons
    watchNamespace: nh-addons
    logLevel: info
#    env:
#      # Disable Kamelets completely
#      - name: KAMEL_INSTALL_DEFAULT_KAMELETS
#        value: "false"
#      - name: KAMEL_KAMELET_CATALOG_ENABLED
#        value: "false"
#      # Skip Kamelet installation entirely
#      - name: KAMEL_KAMELET_CATALOG_REPO
#        value: ""

  platform:
    profile: Kubernetes
    build:
      timeout: 5m
      # Configure registry at platform level
      registry:
        address: ""
    # Explicitly disable Kamelet catalog
#    kamelet:
#      repositories: []

  # Explicitly disable all monitoring and optional features
  monitoring:
    enabled: false

  # Install basic Camel K CRDs (but skip Kamelets)
  installCRDs: true
