camel-k:
  enabled: true

  operator:
    namespace: nh-addons
    logLevel: info
    env:
      # Explicitly enable Kamelets
      - name: KAMEL_INSTALL_DEFAULT_KAMELETS
        value: "true"
      - name: KAMEL_KAMELET_CATALOG_ENABLED
        value: "true"

  # Platform configuration with Kamelet catalog enabled
  platform:
    profile: Kubernetes
    build:
      timeout: 5m
      # Configure registry at platform level
      registry:
        address: "docker.io"
    # Enable standard Kamelet catalog
    kamelet: {}

  # Explicitly disable all monitoring and optional features
  monitoring:
    enabled: false

  # Install basic Camel K CRDs (but skip Kamelets)
  installCRDs: true
