camel-k:
  enabled: true

  # These values will be passed directly to the upstream chart
  operator:
    namespace: nh-addons
    logLevel: info

  # Platform configuration
  platform:
    profile: Kubernetes

    # Disable kamelets due to K8s 1.32 schema compatibility
    kamelet:
      repositories: []

  monitoring:
    enabled: false
