apiVersion: v2
name: openreplay
description: KAOPS addon to install OpenReplay session replay
type: application
version: 0.2.16
appVersion: "v1.26.0"
dependencies:
  - name: databases
    version: "0.1.0"
    repository: "file://./charts/databases"
    condition: databases.enabled
  - name: openreplay
    version: "0.1.0"
    repository: "file://./charts/openreplay"
    condition: openreplay.enabled
