apiVersion: v1
kind: ConfigMap
metadata:
  name: default-n8n-workflows
  labels:
    {{- include "n8n-automation.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "n8n-workflows/*" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{- end }}