metadata:
  slug: 'private-ai'
  name: 'Private AI'
  description: 'Deploy generative AI while safeguarding corporate data and scaling into your own infrastructure.'
  categories: ['Artificial Intelligence']
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/private-ai/logo-dark.png'
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/private-ai/logo-light.png'
  detailUrl: 'https://addons.kaops.net/openwebui/'
  externalUrl: 'https://openwebui.com/'
  isProduction: false
  installTargets:
    hub: true
    hubRequired: true
    edge: false
    clusterMessage: Must be installed on clusters configured for Ingress.

forms: 
  - slug: default
    label: 'Open WebUI configuration'
variables:
  - slug: 'gpuEnabled'
    path: 'open-webui.ollama.ollama.gpu.enabled'
    forms: ['default']
    ui:
      type: 'toggle'
      label: 'Use GPU'
  - slug: 'modelsToPull'
    path: 'open-webui.ollama.ollama.models.pull'
    forms: ['default']
    ui:
      type: 'transferlist'
      label: 'Select LLM Models to Pull'
      sourceLabel: 'LLM Models'
      options: ['gemma2','gemma3:1b','gemma3:4b','llama3.1:8b','llama3.2:3b']
      help: 'Models to pull from: https://ollama.com/search'
      searchable: true
system:
  - path: 'open-webui.ingress.host'
    value: 'chat.${system.hubCluster.ingressHostname}'
    
output:
  - name: Open Web UI URL
    description: 'The URL to access Open WebUI'
    value: 'https://chat.${system.hubCluster.ingressHostname}'
    type: 'url'
    slug: default
