open-webui:
  image:
    repository: nethopper/kaops-open-webui
    tag: latest
  ollama:
    ollama:
      gpu:
        enabled: false
      models:
        pull: []
    service:
      type: ClusterIP
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
      nginx.ingress.kubernetes.io/backend-protocol: http
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/tls-acme: 'true'
    host:
    tls: true
    existingSecret: "webui-tls"
  extraEnvVars:
    - name: WEBUI_NAME
      value: 'Private AI'
    - name: DISABLE_CODE_INTERPRETER
      value: 'true'
    - name: ENABLE_GOOGLE_DRIVE_INTEGRATION
      value: 'true'
    - name: ENABLE_ONEDRIVE_INTEGRATION
      value: 'true'
