metadata:
  slug: 'karpenter'
  displayName: 'Karpenter'
  description: 'Simplify Kubernetes infrastructure with the right nodes at the right time.'
  logoUrlDark: 'https://nh-addons.s3.us-east-1.amazonaws.com/karpenter/logo.png'
  logoUrlLight: 'https://nh-addons.s3.us-east-1.amazonaws.com/karpenter/logo.png'
  detailUrl: 'https://addons.kaops.net/karpenter'
  externalUrl: 'https://opencost.github.io/opencost-helm-chart'
  installTargets:
    hub: true
    hubRequired: true
    edge: false
  
forms: 
  - name: "myform"
    description: "Form for namespace"
    type: standard
  - name: "secrets"
    type: secret
  
variables:
  - name: "networkPolicy"
    description: "Namespace where the application will be deployed"
    form: "myform"
    formKitSchema: ""
    type: "text"
    label: "Namespace"
    required: true
  - name: "pearSecret"
    description: "Secret for pear"
    form: "secrets"
    type: "secret"
    label: "Pear Secret"
    required: true
  - location: "preinstall.secrets.enabled"
    description: "Secret for pear"
    form: "secrets"
    type: "secret"
    label: "Pear Secret"
    required: true

dependencies:
    features:
      - name: 'grafana'
        required: false
      - name: 'sealed-secrets'
        required: true
