open-webui:
  image:
    repository: nethopper/kaops-open-webui
    tag: git-d3fb5d3
    pullPolicy: Always
  ollama:
    ollama:
      gpu:
        enabled: false
      models:
        pull: []
    service:
      type: ClusterIP
  ingress:
    enabled: true
  extraEnvVars:
    - name: WEBUI_NAME
      value: "Private AI"
    - name: ENABLE_CODE_EXECUTION
      value: "false"
    - name: ENABLE_CODE_INTERPRETER
      value: "false"
    - name: ENABLE_GOOGLE_DRIVE_INTEGRATION
      value: "true"
    - name: ENABLE_ONEDRIVE_INTEGRATION
      value: "true"
    - name: BYPASS_EMBEDDING_AND_RETRIEVAL
      value: "true"
    - name: WEBUI_AUTH
      value: "false"
