apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "metrics-exporter.fullname" . }}-cronjob
  labels: 
    {{- include "metrics-exporter.fullname" . | nindent 4 }}
spec:
  schedule: {{ .Values.job.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: node-runner
              image: node:23.10.0
              workingDir: /app
              volumeMounts:
                - name: scripts
                  mountPath: /app
              command: [ "sh", "-c", "cp package.json /tmp && npm install --prefix /tmp && npm start" ]
              env:
                - name: NODE_PATH
                  value: /tmp/node_modules
              envFrom:
                - secretRef: 
                    name: {{ include "metrics-exporter.fullname" . }}-secret
                - secretRef:
                    name: {{ .Values.opencost.cloudIntegrationSecret }}
          volumes:
            - name: scripts
              configMap:
                name: {{ include "metrics-exporter.fullname" . }}-scripts