apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-exporter.fullname" . }}-secret-s3-envs
  labels: 
    {{- include "metrics-exporter.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc }}