{{- if and (hasKey .Values "s3") (or (hasKey .Values.s3 "accessKeyId") (hasKey .Values.s3 "secretAccessKey")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-exporter.fullname" . }}-secret-s3-envs
  labels: 
    {{- include "metrics-exporter.labels" . | nindent 4 }}
data:
  {{- if and (hasKey .Values.s3 "accessKeyId") (.Values.s3.accessKeyId) }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc }}
  {{- end }}
  {{- if and (hasKey .Values.s3 "secretAccessKey") (.Values.s3.secretAccessKey) }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
  {{- end }}
{{- end }}