metadata:
  slug: foobar
  name: Foo Bar GCS
  description: Minimal synchronization from Google Drive to Google Cloud Storage
  categories: [Integration]
  isProduction: false
  installTargets:
    clusterMessage: Works on standard Kubernetes including GKE.
    infoMessage: This addon requires the Camel K addon to be installed first.

forms:
  - slug: default
    label: Configuration
    steps:
      - slug: basic
        variableSlugs:
          - driveClientId
          - googleCredentialsSecret
        ui:
          label: Basic

variables:
  - slug: driveClientId
    path: driveClientId
    forms: [default]
    ui:
      type: text
      label: Google Drive ID
      validation: required
  - slug: googleCredentialsSecret
    path: googleCredentialsSecret
    forms: [default]
    ui:
      type: secret
      label: Google Credentials
      help: Base64-encoded Google service account credentials JSON file with access to Google Drive and GCS
      validation: required


system:

output:

dependencies:
  addons:
    - slug: 'camel-k'
      name: 'Apache Camel K'
      required: true
